const fs = require("fs");
const cloudinary = require("cloudinary").v2;
const keys = require("../config/keys");
const { generateSecureFilename } = require("../middleware/uploadSecurity");

// Cấu hình Cloudinary
cloudinary.config({
  cloud_name: keys.CLOUDINARY_NAME,
  api_key: keys.CLOUDINARY_API_KEY,
  api_secret: keys.CLOUDINARY_API_SECRET,
});

/**
 * Upload images with security validation
 * Validates file, generates secure filename, and uploads to Cloudinary
 * 
 * Requirements: 11.1-11.5
 */
exports.uploadImages = async (req, res) => {
  try {
    const { path: uploadPath } = req.body;
    const file = req.files.file;
    let images = [];

    // Use secure filename generated by middleware or generate new one
    const secureFilename = req.secureFilename || generateSecureFilename(file.name);

    const url = await uploadToCloudinary(file, uploadPath, secureFilename);
    images.push(url);

    removeTmp(file);
    
    // Set proper Content-Type header for JSON response
    res.setHeader('Content-Type', 'application/json');
    res.json(images);
  } catch (error) {
    console.error("Upload error:", error);
    // Return generic error message without exposing system details
    return res.status(500).json({ message: "File upload failed" });
  }
};

/**
 * Upload file to Cloudinary with secure filename
 * @param {Object} file - File object with tempFilePath
 * @param {string} uploadPath - Cloudinary folder path
 * @param {string} secureFilename - Secure filename to use
 * @returns {Promise<Object>} Upload result with secure URL
 */
const uploadToCloudinary = async (file, uploadPath, secureFilename) => {
  return new Promise((resolve, reject) => {
    cloudinary.uploader.upload(
      file.tempFilePath,
      {
        folder: uploadPath || "blog",
        resource_type: "auto",
        public_id: secureFilename.replace(/\.[^/.]+$/, ""), // Remove extension for Cloudinary
      },
      (error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve({ url: result.secure_url });
        }
      }
    );
  });
};

const removeTmp = (file) => {
  fs.unlink(file.tempFilePath, (err) => {
    if (err) console.error("Remove temp file error:", err);
  });
};
